      SUBROUTINE CPOLYEV(NN,S,P,PV)
C EVALUATES A COMPLEX POLYNOMIAL  P  AT  S  BY THE HORNER RECURRENCE
C PLACING THE PARTIAL SUMS IN Q AND THE COMPUTED VALUE IN PV.
      INTEGER NN,I
      DOUBLE PRECISION P(NN)
      DOUBLE COMPLEX S,PV
      PV = DCMPLX(P(1),0)
      DO 10 I = 2,NN
          PV = PV*S+P(I)
   10 CONTINUE
      RETURN
      END
