      SUBROUTINE CPOLYEV2(NN,S1,S2,P,PV1,PV2)
C EVALUATES A COMPLEX POLYNOMIAL  P  AT  S  BY THE HORNER RECURRENCE
C PLACING THE PARTIAL SUMS IN Q AND THE COMPUTED VALUE IN PV.
      INTEGER NN,I
      DOUBLE PRECISION P(NN)
      DOUBLE COMPLEX S1,S2,PV1,PV2
      PV1 = DCMPLX(P(1),0)
      PV2 = PV1
      DO 10 I = 2,NN
          PV1 = PV1*S1+P(I)
          PV2 = PV2*S2+P(I)
   10 CONTINUE
      RETURN
      END
