C      SUBROUTINE WEIDEMAN(XI, YI, U, V, FLAG)
C  GIVEN A COMPLEX NUMBER Z = (XI,YI), THIS SUBROUTINE COMPUTES
C  THE VALUE OF THE FADDEEVA-FUNCTION W(Z) = EXP(-Z**2)*ERFC(-I*Z),
C  WHERE ERFC IS THE COMPLEX COMPLEMENTARY ERROR-FUNCTION AND I
C  MEANS SQRT(-1).THE ALGORITHM IS BASED ON THE PAPER PUBLISHED ON
C  SIAM JOURNAL ON NUMERICAL ANALYSIS VOL.31 NO.5 PP.1497-1518,OCTOBER
C  1994 BY J.A.C. WEIDEMAN.THE USER CAN CHOOSE BETWEEN N=4, N=8 AND N=16.
      SUBROUTINE WOFZMW(Z1,Z2,RES,M,MW,FLAG)
      INTEGER M,MW
      DOUBLE COMPLEX Z1,Z2,RES,ZZ1,ZZ2
      LOGICAL FLAG
      FLAG=.FALSE.
      SELECT CASE(MW)
      CASE(1)
         CALL WOFZH(Z1,ZZ1,FLAG)
         CALL WOFZH(Z2,ZZ2,FLAG)
      CASE(4)
         CALL WOFZWH4(Z1,ZZ1,FLAG)
         CALL WOFZWH4(Z2,ZZ2,FLAG)
      CASE(8)
         CALL WOFZWH8(Z1,ZZ1,FLAG)
         CALL WOFZWH8(Z2,ZZ2,FLAG)
      CASE(16)
         CALL WOFZWH16(Z1,ZZ1,FLAG)
         CALL WOFZWH16(Z2,ZZ2,FLAG)
      END SELECT
      RES=(ZZ1*Z1**M-ZZ2*Z2**M)/(Z1-Z2)
      FLAG=.TRUE.
      RETURN
      END
